"""
Interactive config wizard. Generates config.py from user input.
Cross-platform (Windows / Linux / macOS).

Run: python -m whatsapp_agent.setup_config
"""
import os
import re
import sys


CONFIG_PATH = "config.py"


def ask(label: str, default: str = "", required: bool = True) -> str:
    suffix = f" [{default}]" if default else ""
    while True:
        val = input(f"  {label}{suffix}: ").strip()
        if not val:
            val = default
        if val or not required:
            return val
        print("    -> required, please try again.")


def normalize_phone(raw: str) -> str:
    digits = re.sub(r"\D", "", raw)
    if not digits:
        return ""
    return digits


def normalize_host(raw: str) -> str:
    raw = raw.strip().rstrip("/")
    if not (raw.startswith("http://") or raw.startswith("https://")):
        return ""
    return raw


def write_config(cfg: dict) -> None:
    template = f'''# ============================================================
# WhatsApp Claude Agent - config.py (generated by setup_config.py)
# ============================================================
# DO NOT commit this file (already in .gitignore).
# To regenerate: delete config.py and run `python -m whatsapp_agent.setup_config`.
# ============================================================

CMD_TOKEN = {cfg["cmd_token"]!r}
SIGNATURE = {cfg["signature"]!r}
API_HOST = {cfg["api_host"]!r}

SESSIONS = {{
    "1": {{
        "token":    {cfg["token"]!r},
        "phone":    {cfg["phone"]!r},
        "lid":      {cfg["lid"]!r},
    }},
}}

OPENAI_API_KEY = {cfg["openai_key"]!r}

ALLOWED_PHONE = SESSIONS["1"]["phone"]
ALLOWED_LID   = SESSIONS["1"]["lid"]
API_TOKEN     = SESSIONS["1"]["token"]
'''
    with open(CONFIG_PATH, "w", encoding="utf-8") as f:
        f.write(template)


def main() -> int:
    print("")
    print("=" * 60)
    print("WhatsApp Claude Agent - Interactive Setup")
    print("=" * 60)
    print("")

    if os.path.exists(CONFIG_PATH):
        ans = input(f"  {CONFIG_PATH} already exists. Overwrite? [y/N]: ").strip().lower()
        if ans not in ("y", "yes"):
            print("  Cancelled. config.py kept.")
            return 0
        print("")

    print("Fill in the values below. Press Enter to accept the default")
    print("shown in [brackets].")
    print("")

    print("--- Optional command token (legacy) ---")
    print("Used to gate /commands. Leave blank - the phone whitelist alone")
    print("is enough for self-chat.")
    cmd_token = ask("CMD_TOKEN [skip]", default="", required=False)
    print("")

    print("--- WhatsApp HTTP API (MBKCHAT / WuzAPI) ---")
    print("Base URL and user token of your WhatsApp HTTP API.")
    while True:
        host_raw = ask("API base URL", default="https://mbkchat.com.br")
        host = normalize_host(host_raw)
        if host:
            break
        print("    -> invalid URL: must start with http:// or https://")
    token = ask("API token")
    print("")

    print("--- WhatsApp number ---")
    print("Your own WhatsApp number - the agent only replies to messages")
    print("from/to this number.")
    phone_raw = ask("Phone in international format, digits only (e.g. 5511999999999)")
    phone     = normalize_phone(phone_raw)
    if not phone:
        print("  ERROR: invalid phone number.")
        return 1
    print("")

    print("--- Audio transcription (optional) ---")
    print("Required only if you want to send voice messages. Get a key at")
    print("https://platform.openai.com/api-keys.")
    openai_key = ask("OPENAI_API_KEY [skip]", default="", required=False)

    cfg = {
        "cmd_token": cmd_token,
        "signature": "*Claude Code*",
        "api_host": host,
        "token":     token,
        "phone":     phone,
        "lid":       "",
        "openai_key": openai_key,
    }

    write_config(cfg)
    print("")
    print(f"  OK - {CONFIG_PATH} created.")
    print("")
    print("Next steps:")
    print("  1. Run: python scripts/bootstrap.py")
    print("     (starts webhook + Quick Tunnel + pushes URL to your")
    print("      provider - one command)")
    print("  2. Send a WhatsApp message to yourself")
    print("  3. Run: python -m whatsapp_agent.discover_lid")
    print("     (auto-detects your LID and updates config.py)")
    print("  4. Open Claude Code and paste in the first message:")
    print("     'Read CLAUDE_PROMPT.md and run the step 2 prompt. SESSION: 1'")
    print("")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except KeyboardInterrupt:
        print("\n  Cancelled.")
        sys.exit(130)
